---
- import_tasks: directories.yml
  tags: laravel-install-directories

- name: Create .env file
  template:
    src: "env.j2"
    dest: "/tmp/{{ item.key }}.env"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
  with_dict: "{{ laravel_apps }}"

- name: Copy .env file into web root
  command: rsync -ac --info=NAME /tmp/{{ item.key }}.env {{ www_root }}/{{ item.key }}/current/.env
  with_dict: "{{ laravel_apps }}"
  register: env_file
  changed_when: env_file.stdout == "{{ item.key }}.env"

- name: Install Dependencies with Composer
  composer:
    no_dev: no
    optimize_autoloader: no
    working_dir: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/"
  become: no
  with_dict: "{{ laravel_apps }}"
